import { defineField, defineType } from "sanity";
import { paymentPlanField, seoFields } from "@/sanity/schemas/objects";

export const property = defineType({
  name: "property",
  title: "Properties",
  type: "document",
  fields: [
    defineField({ name: "title", title: "Property Name", type: "string", validation: (Rule) => Rule.required() }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "title", maxLength: 96 }, validation: (Rule) => Rule.required() }),
    defineField({ name: "reference", title: "Property ID", type: "string", validation: (Rule) => Rule.required() }),
    defineField({ name: "shortDescription", title: "Short Description", type: "text", rows: 3 }),
    defineField({ name: "description", title: "Full Description", type: "text", rows: 6 }),
    defineField({ name: "type", title: "Property Type", type: "string", options: { list: ["Residential", "Land", "Commercial", "Apartment", "Luxury Home", "Development", "Investment"] } }),
    defineField({ name: "category", title: "Category", type: "reference", to: [{ type: "category" }] }),
    defineField({ name: "status", title: "Property Status", type: "string", initialValue: "Available", options: { list: ["Available", "New Listing", "Featured", "Reserved", "Sold", "Coming Soon", "Off Plan", "Under Construction", "Price Reduced"] } }),
    defineField({ name: "featured", title: "Feature this property", type: "boolean", initialValue: false }),
    defineField({ name: "archived", title: "Archive property", type: "boolean", initialValue: false }),
    defineField({ name: "price", title: "Price", type: "number" }),
    defineField({ name: "currency", title: "Currency", type: "string", initialValue: "NGN" }),
    defineField({ name: "priceLabel", title: "Price Label", type: "string", description: "Use for 'From ₦45M', rent periods, or price per plot." }),
    defineField({ name: "location", title: "Saved Location", type: "reference", to: [{ type: "location" }] }),
    defineField({ name: "address", title: "Address", type: "string" }),
    defineField({ name: "neighbourhood", title: "Neighbourhood", type: "string" }),
    defineField({ name: "city", title: "City", type: "string" }),
    defineField({ name: "state", title: "State", type: "string" }),
    defineField({ name: "latitude", title: "Latitude", type: "number" }),
    defineField({ name: "longitude", title: "Longitude", type: "number" }),
    defineField({ name: "mapUrl", title: "Google Maps Link / Embed URL", type: "url" }),
    defineField({ name: "bedrooms", title: "Bedrooms", type: "number" }),
    defineField({ name: "bathrooms", title: "Bathrooms", type: "number" }),
    defineField({ name: "toilets", title: "Toilets", type: "number" }),
    defineField({ name: "parking", title: "Parking Spaces", type: "number" }),
    defineField({ name: "propertySize", title: "Property Size", type: "string" }),
    defineField({ name: "landSize", title: "Land Size / Plot Size", type: "string" }),
    defineField({ name: "landTitle", title: "Land Title", type: "string" }),
    defineField({ name: "surveyInformation", title: "Survey Information", type: "text", rows: 3 }),
    defineField({ name: "developmentStatus", title: "Development Status", type: "string" }),
    defineField({ name: "roadAccess", title: "Road Access", type: "string" }),
    defineField({ name: "estateName", title: "Estate Name", type: "string" }),
    defineField({ name: "allocationInformation", title: "Allocation Information", type: "text", rows: 3 }),
    defineField({ name: "plotsAvailable", title: "Number of Plots Available", type: "number" }),
    defineField({ name: "furnishing", title: "Furnishing", type: "string" }),
    defineField({ name: "condition", title: "Property Condition", type: "string" }),
    defineField({ name: "yearBuilt", title: "Year Built", type: "number" }),
    defineField({ name: "commercialSubtype", title: "Commercial Subtype", type: "string", options: { list: ["Office", "Retail", "Warehouse", "Hotel", "Industrial", "Mixed use", "Commercial land"] } }),
    defineField({ name: "floors", title: "Floors", type: "number" }),
    defineField({ name: "occupancyStatus", title: "Occupancy Status", type: "string" }),
    defineField({ name: "featuredImage", title: "Featured Image", type: "image", options: { hotspot: true } }),
    defineField({ name: "gallery", title: "Gallery", type: "array", of: [{ type: "image", options: { hotspot: true } }] }),
    defineField({ name: "videoUrl", title: "Video URL", type: "url" }),
    defineField({ name: "virtualTourUrl", title: "Virtual Tour URL", type: "url" }),
    defineField({ name: "amenities", title: "Amenities", type: "array", of: [{ type: "reference", to: [{ type: "amenity" }] }] }),
    defineField({ name: "features", title: "Features", type: "array", of: [{ type: "string" }] }),
    paymentPlanField,
    defineField({ name: "nearbyLandmarks", title: "Nearby Landmarks", type: "array", of: [{ type: "string" }] }),
    defineField({ name: "documents", title: "Property Documents", type: "array", of: [{ type: "object", fields: [defineField({ name: "title", type: "string" }), defineField({ name: "file", type: "file" })] }] }),
    defineField({ name: "brochure", title: "Brochure", type: "file" }),
    defineField({ name: "agent", title: "Property Agent", type: "reference", to: [{ type: "agent" }] }),
    defineField({ name: "datePublished", title: "Date Published", type: "datetime" }),
    ...seoFields
  ],
  preview: { select: { title: "title", subtitle: "reference", media: "featuredImage" } }
});
